var questions = [
    false,
    ["≞", "The mathematical synbol for \"Measured by\""],
    ["↭", "Left/Right Wave arrow"],
    ["⊜", "Circled equals sign"],
    false,
    ["ȹ", "A ligature from the letters q and p."],
    false,
    ["⅍", "A synbol for the danish word Aktieselskab, meaning a stock-based company. (uppercase)"],
    false,
    ["⏕", "A symbol noting a verse consisting of a dactyl."],
    ["⎃", "A symbol representing emphasis"],
    ["⇪", "Symbol for caps lock"],
    ["ȵ", "The voiced palatal nasal, which is a type of consonant used in some spoken languages."],
    false,
    false,
    false,
    ["⍥", "An APL syntax symbol"],
    false,
    ["☈", "A symbol for thunderstorm."],
    false,
    false,
    ["⚶", "The planet symbol for Vesta"],
    false,
    false,
    ["∢", "Symbol for a spherical angle"],
    false,
    ["⌫", "Backspace Symbol"],
    false,
    false,
    false,
    false,
    false,
    ["⌬", "Alternative symbol for Benzene"],
    false,
    ["⏏", "Symbol for removable media"],
    false,
    ["∏", "A symbol representing a product over a set of terms."],
    ["⏣", "Symbol for Benzene"],
    ["⇧", "A symbol dictating an arrow pointing upwards"],
    false,
    ["⋒", "Double Intersection. Mathematical Operators."],
    ["ᴥ", "The Latin letter Ain"],
    false,
    false,
    ["♞", "The black knight piece in chess"],
    ["⛟", "Symbol for a truck/lorry"],
    ["⍝", "An APL syntax symbol"],
    false,
    false,
    false,
    false,
    ["ↈ", "The way to write 100,000 in roman numerals"],
    ["⛚", "A drive slow sign"],
    ["✆", "The telephone location sign"],
    false,
    false,
    ["⊛", "Circled asterisk."],
    false,
    false,
    ["℁", "A symbol representing the phrase \"Addressed to the subject\"."],
    false,
    ["❡", "An ornamental pilcrow ( ¶ ) with a leftward-curling descender "],
    false,
    false,
    ["ඞ", "A character from the Sinhalese language which makes a \"ṅa\" sound, and it's looking kinda sus..."],
    ["m", "Thirteenth letter of the modern English alphabet and the ISO basic Latin alphabet."],
    ["⍾", "Electric Bell Symbol"],
    ["℻", "A symbol to indicate a fax machine"],
];

var answers = {};
if (localStorage.hasOwnProperty('symbolQuizAnswers'))
    answers = JSON.parse(localStorage.symbolQuizAnswers); //load save
else
    localStorage.symbolQuizAnswers = '{}'; //if no save, create a new one