var questions = [
    "Raragraph",
    ["≞", "The mathematical symbol for \"Measured by\""],
    ["↭", "Left/Right Wave arrow"],
    ["⊜", "Circled equals sign"],
    "But how are people gonna know what my flash drive looks like if I don't have a symbol to represent it!?",
    ["ȹ", "A ligature from the letters q and p."],
    "We have ➀, ➁, ➂, ... ⑱, ⑲, and ⑳, but it mysteriously stops at 20.",
    ["⅍", "A symbol for the danish word Aktieselskab, meaning a stock-based company. (uppercase)"],
    "A cropped ladder or a cropped rail? Your choice.",
    ["⏕", "A symbol noting a verse consisting of a dactyl."],
    ["⎃", "A symbol representing emphasis"],
    ["⇪", "Symbol for caps lock"],
    ["ȵ", "The voiced palatal nasal, which is a type of consonant used in some spoken languages."],
    "A Floob! Don't you think the internet would be a much better place if this were real?",
    "Pokémon trading is a pretty specific use case, don't you think?",
    "There are no symbols of numbers with double exclamation marks after them.",
    ["⍥", "An APL syntax symbol"],
    "Arrow and no bow",
    ["☈", "A symbol for thunderstorm."],
    "This one would be a favourite among both electricians and magicians.",
    "This one would be a favourite among both mathematicians and Nintendo fans.",
    ["⚶", "The planet symbol for Vesta"],
    "Unicode is seriously lacking in lil' guys.",
    "brige",
    ["∢", "Symbol for a spherical angle"],
    "He's just a lil' guy! Please Unicode, let him be your next character!",
    ["⌫", "Backspace Symbol"],
    "Ok.",
    "W!",
    "Alternate universe music notation.",
    "I just need to be directed to the right, don't need anything too fancy.",
    "Alternate universe ancient artifact",
    ["⌬", "Alternative symbol for Benzene"],
    "Okay, this one's just advertising that it's FAKE.",
    ["⏏", "Symbol for removable media (eject)"],
    "The bishop from chess, but just the hat.",
    ["∏", "A symbol representing a product over a set of terms."],
    ["⏣", "Symbol for Benzene"],
    ["⇧", "A symbol dictating an arrow pointing upwards"],
    "Oh my god it's that one thing!",
    ["⋒", "Double Intersection. Mathematical Operators."],
    ["ᴥ", "The Latin letter Ain"],
    "This one would be difficult to balance.",
    "There are *, ⁑, ⁂, and that's it.",
    ["♞", "The black knight piece in chess"],
    ["⛟", "Symbol for a truck/lorry"],
    ["⍝", "An APL syntax symbol"],
    "In an alternate universe where omnitrixes are real and commonplace...",
    "If you want two squares you can just put them one after the other.",
    "Bike light",
    "Ice cream",
    ["ↈ", "The way to write 100,000 in roman numerals"],
    ["⛚", "A drive slow sign"],
    ["✆", "The telephone location sign"],
    "What is this A shouting? Its own name? We may never know...",
    "soi soi soi soi soi soi soi soi soi soi soi soi soi soi soi soi",
    ["⊛", "Circled asterisk."],
    "Alternate universe four-leaf suit of clubs.",
    "Legally ambiguous monster-capturing device.",
    ["℁", "A symbol representing the phrase \"Addressed to the subject\"."],
    "There are no symbols of numbers with a single exclamation mark after them.",
    ["❡", "An ornamental pilcrow ( ¶ ) with a leftward-curling descender "],
    "They've got their own little cubby!",
    "For when you get into one of those pulling arguments.",
    ["ඞ", "A character from the Sinhalese language which makes a \"ṅa\" sound, and it's looking kinda sus..."],
    ["m", "Thirteenth letter of the modern English alphabet and the ISO basic Latin alphabet."],
    ["⍾", "Electric Bell Symbol"],
    ["℻", "A symbol to indicate a fax machine"],
];

var answers = {};
if (localStorage.hasOwnProperty('symbolQuizAnswers'))
    answers = JSON.parse(localStorage.symbolQuizAnswers); //load save
else
    localStorage.symbolQuizAnswers = '{}'; //if no save, create a new one